package tor

import (
	"fmt"
	"path/filepath"
	"strings"
)

// InstanceConfig is everything needed to render one tor instance's torrc.
type InstanceConfig struct {
	// Index identifies the instance within the pool.
	Index int
	// DataDirectory holds this instance's state. Each instance needs its own:
	// two tor processes sharing one directory will not start.
	DataDirectory string
	// SocksPort and ControlPort are bound on loopback only.
	SocksPort   int
	ControlPort int

	ExitNodes        string
	ExcludeExitNodes string
	StrictNodes      bool

	// ExtraConfig is appended verbatim, for options this struct does not model.
	ExtraConfig string
}

// CookiePath returns the control auth cookie's location for this instance.
func (ic InstanceConfig) CookiePath() string {
	return filepath.Join(ic.DataDirectory, "control_auth_cookie")
}

// TorrcPath returns where this instance's torrc is written.
func (ic InstanceConfig) TorrcPath() string {
	return filepath.Join(ic.DataDirectory, "torrc")
}

// ControlAddr returns the loopback address of this instance's control port.
func (ic InstanceConfig) ControlAddr() string {
	return fmt.Sprintf("127.0.0.1:%d", ic.ControlPort)
}

// SocksAddr returns the loopback address of this instance's SOCKS port.
func (ic InstanceConfig) SocksAddr() string {
	return fmt.Sprintf("127.0.0.1:%d", ic.SocksPort)
}

// Torrc renders the configuration file for this instance.
//
// Both ports bind 127.0.0.1 unconditionally. These are internal ports reached
// only by torpool inside the same container; binding them anywhere else would
// expose an unauthenticated-by-design control port to the network.
func (ic InstanceConfig) Torrc() string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by torpool for instance %d. Do not edit.\n\n", ic.Index)

	fmt.Fprintf(&b, "DataDirectory %s\n", ic.DataDirectory)
	fmt.Fprintf(&b, "SocksPort %s\n", ic.SocksAddr())
	fmt.Fprintf(&b, "ControlPort %s\n", ic.ControlAddr())

	// Cookie auth rather than a hashed password: the control port is loopback
	// only, so there is no password to manage and no hash to bake in. The
	// cookie is chmod 0600 and owned by the tor user.
	b.WriteString("CookieAuthentication 1\n")

	// The SOCKS port only ever sees connections from torpool itself.
	b.WriteString("SocksPolicy accept 127.0.0.1\nSocksPolicy reject *\n")

	// Every instance must pick its own guards, or the whole pool shares one
	// entry point and the exit diversity we are paying for shrinks.
	b.WriteString("\n# Independent guard selection per instance.\n")
	b.WriteString("UseEntryGuards 1\n")

	if ic.ExitNodes != "" {
		fmt.Fprintf(&b, "ExitNodes %s\n", ic.ExitNodes)
	}
	if ic.ExcludeExitNodes != "" {
		fmt.Fprintf(&b, "ExcludeExitNodes %s\n", ic.ExcludeExitNodes)
	}
	if ic.StrictNodes {
		b.WriteString("StrictNodes 1\n")
	}

	b.WriteString("\nLog notice stderr\n")

	if extra := strings.TrimSpace(ic.ExtraConfig); extra != "" {
		b.WriteString("\n# From TOR_EXTRA_CONFIG\n")
		b.WriteString(extra)
		b.WriteString("\n")
	}
	return b.String()
}
